'use client';

import { useState } from 'react';
import { BarChart3, Copy, Check } from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogDescription,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { usePomodoroStore } from '@/stores/pomodoro';
import { toast } from '@/hooks/use-toast';

export function SessionStatsDialog() {
  const { completedWorkSessions, settings } = usePomodoroStore();
  const [copied, setCopied] = useState(false);

  const totalFocusMinutes = completedWorkSessions * settings.workDuration;
  
  // Calculate break time (rough estimate based on sessions)
  const shortBreaks = Math.max(0, completedWorkSessions - Math.floor(completedWorkSessions / settings.longBreakInterval));
  const longBreaks = Math.floor(completedWorkSessions / settings.longBreakInterval);
  const totalBreakMinutes = (shortBreaks * settings.shortBreakDuration) + (longBreaks * settings.longBreakDuration);

  const statsMarkdown = `## 🍅 Pomodoro Statistics - ${new Date().toLocaleDateString()}

- **Total Sessions:** ${completedWorkSessions}
- **Total Focus Time:** ${totalFocusMinutes} minutes
- **Total Break Time:** ${totalBreakMinutes} minutes
- **Efficiency:** ${completedWorkSessions > 0 ? 'High' : 'N/A'}

*Generated by Pomodoro Focus*`;

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(statsMarkdown);
      setCopied(true);
      toast({
        title: "Copied to clipboard",
        description: "Statistics have been copied in Markdown format.",
      });
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy!', err);
    }
  };

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button
          variant="ghost"
          size="icon"
          className="h-6 w-6 rounded-full text-muted-foreground/60 hover:text-foreground hover:bg-accent ml-1"
        >
          <BarChart3 className="h-3.5 w-3.5" />
        </Button>
      </DialogTrigger>
      <DialogContent className="bg-card border-border sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Today's Statistics</DialogTitle>
          <DialogDescription>
            A summary of your productivity sessions for today.
          </DialogDescription>
        </DialogHeader>
        
        <div className="grid gap-4 py-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="flex flex-col gap-1 p-3 rounded-xl bg-muted/50 border border-border/50">
              <span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground/70">Sessions</span>
              <span className="text-2xl font-bold text-pomodoro-work">{completedWorkSessions}</span>
            </div>
            <div className="flex flex-col gap-1 p-3 rounded-xl bg-muted/50 border border-border/50">
              <span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground/70">Focus Time</span>
              <span className="text-2xl font-bold text-pomodoro-work">{totalFocusMinutes} <span className="text-xs font-normal text-muted-foreground">min</span></span>
            </div>
            <div className="flex flex-col gap-1 p-3 rounded-xl bg-muted/50 border border-border/50">
              <span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground/70">Break Time</span>
              <span className="text-2xl font-bold text-pomodoro-short">{totalBreakMinutes} <span className="text-xs font-normal text-muted-foreground">min</span></span>
            </div>
            <div className="flex flex-col gap-1 p-3 rounded-xl bg-muted/50 border border-border/50">
              <span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground/70">Total Time</span>
              <span className="text-2xl font-bold text-foreground">{totalFocusMinutes + totalBreakMinutes} <span className="text-xs font-normal text-muted-foreground">min</span></span>
            </div>
          </div>
        </div>

        <div className="flex justify-end pt-2">
          <Button 
            onClick={copyToClipboard}
            className="gap-2 bg-secondary hover:bg-accent text-foreground border border-border/50"
          >
            {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
            {copied ? 'Copied!' : 'Copy Markdown'}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
